### ISSUE TITLE
Move from Files to Database

### ISSUE THREAD

**Issue by johneastman** [johneastman/todo-backend#3]
# TODO
- [x] Verify functionality works on PythonAnywhere
- [x] Move data from files to db
    * Use Bruno to make a request 
- [ ] ~~Update unit tests~~
    * ~~Need to mock a MySQL database connection for the tests~~

**Comment by johneastman** [comment]
I'll try fixing the unit tests in a separate task
